"""Generate comprehensive biomechanical analysis reports."""

from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime
import os
from typing import Dict, List

class BiomechanicalReportGenerator:
    """Generate PDF reports for biomechanical analysis."""

    def __init__(self, output_path: str = "MotionMetrics_Biomechanical_Analysis_Report.pdf"):
        """Initialize report generator."""
        self.output_path = output_path
        self.doc = SimpleDocTemplate(output_path, pagesize=A4)
        self.styles = getSampleStyleSheet()
        self.story = []

        # Custom styles
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=1,  # Center
            textColor=colors.darkblue
        )

        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceAfter=12,
            textColor=colors.darkblue
        )

    def add_title_page(self, csv_file_path: str):
        """Add title page to report."""
        title = Paragraph("MotionMetrics - Biomechanical Motion Analysis Report", self.title_style)
        self.story.append(title)
        self.story.append(Spacer(1, 0.5 * inch))

        # Analysis details
        details = [
            f"<b>Analysis Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"<b>Data Source:</b> {os.path.basename(csv_file_path)}",
            f"<b>Analysis Type:</b> 3D Human Motion Analysis",
            f"<b>Generated by:</b> MotionMetrics - Biomechanical Analyzer v1.0"
        ]

        for detail in details:
            para = Paragraph(detail, self.styles['Normal'])
            self.story.append(para)
            self.story.append(Spacer(1, 0.2 * inch))

        self.story.append(PageBreak())

    def add_summary_section(self, data_stats: Dict):
        """Add data summary section."""
        heading = Paragraph("Data Summary", self.heading_style)
        self.story.append(heading)

        # Create summary table
        summary_data = [
            ['Metric', 'Value'],
            ['Total Data Points', str(data_stats.get('total_points', 'N/A'))],
            ['Time Duration', f"{data_stats.get('duration', 0):.2f} seconds"],
            ['Frame Rate', f"{data_stats.get('fps', 40)} fps"],
            ['Available Keypoints', str(len(data_stats.get('available_keypoints', [])))],
            ['Analysis Date', datetime.now().strftime('%Y-%m-%d')]
        ]

        table = Table(summary_data, colWidths=[2 * inch, 2 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        self.story.append(table)
        self.story.append(Spacer(1, 0.3 * inch))

    def add_movement_analysis(self, movement_stats: Dict, chart_paths: List[str]):
        """Add movement analysis section."""
        heading = Paragraph("Movement Analysis", self.heading_style)
        self.story.append(heading)

        # Add description
        description = """
        This section presents the analysis of bilateral movement patterns for selected keypoint pairs.
        The charts show position changes over time in three dimensions (X, Y, Z coordinates).
        """
        para = Paragraph(description, self.styles['Normal'])
        self.story.append(para)
        self.story.append(Spacer(1, 0.2 * inch))

        # Add charts
        for chart_path in chart_paths:
            if os.path.exists(chart_path):
                try:
                    img = Image(chart_path, width=6 * inch, height=4.5 * inch)
                    self.story.append(img)
                    self.story.append(Spacer(1, 0.2 * inch))
                except Exception as e:
                    print(f"Warning: Could not add image {chart_path}: {e}")

        # Add movement statistics table
        if movement_stats:
            stats_heading = Paragraph("Movement Statistics", self.styles['Heading3'])
            self.story.append(stats_heading)

            for pair_name, stats in movement_stats.items():
                pair_heading = Paragraph(f"{pair_name} Statistics", self.styles['Heading4'])
                self.story.append(pair_heading)

                stats_data = [
                    ['Metric', 'Left', 'Right'],
                    ['X Range (mm)', f"{stats['left_stats']['x_range']:.1f}", f"{stats['right_stats']['x_range']:.1f}"],
                    ['Y Range (mm)', f"{stats['left_stats']['y_range']:.1f}", f"{stats['right_stats']['y_range']:.1f}"],
                    ['Z Range (mm)', f"{stats['left_stats']['z_range']:.1f}", f"{stats['right_stats']['z_range']:.1f}"],
                    ['X Mean (mm)', f"{stats['left_stats']['x_mean']:.1f}", f"{stats['right_stats']['x_mean']:.1f}"],
                    ['Y Mean (mm)', f"{stats['left_stats']['y_mean']:.1f}", f"{stats['right_stats']['y_mean']:.1f}"],
                    ['Z Mean (mm)', f"{stats['left_stats']['z_mean']:.1f}", f"{stats['right_stats']['z_mean']:.1f}"]
                ]

                table = Table(stats_data, colWidths=[1.5 * inch, 1 * inch, 1 * inch])
                table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black)
                ]))

                self.story.append(table)
                self.story.append(Spacer(1, 0.2 * inch))

    def add_joint_angle_analysis(self, joint_stats: Dict, chart_path: str = None):
        """Add joint angle analysis section."""
        heading = Paragraph("Joint Angle Analysis", self.heading_style)
        self.story.append(heading)

        description = """
        Joint angles are calculated using three-point angle measurements between connected body segments.
        These measurements provide insights into joint mobility and movement patterns.
        """
        para = Paragraph(description, self.styles['Normal'])
        self.story.append(para)
        self.story.append(Spacer(1, 0.2 * inch))

        # Add joint angle chart
        if chart_path and os.path.exists(chart_path):
            try:
                img = Image(chart_path, width=6 * inch, height=6 * inch)
                self.story.append(img)
                self.story.append(Spacer(1, 0.2 * inch))
            except Exception as e:
                print(f"Warning: Could not add joint angle chart: {e}")

        # Add joint angle statistics
        if joint_stats:
            stats_data = [['Joint', 'Mean Angle (°)', 'Std Dev (°)', 'Min Angle (°)', 'Max Angle (°)']]

            for joint_name, stats in joint_stats.items():
                stats_data.append([
                    joint_name,
                    f"{stats['mean']:.1f}",
                    f"{stats['std']:.1f}",
                    f"{stats['min']:.1f}",
                    f"{stats['max']:.1f}"
                ])

            table = Table(stats_data, colWidths=[1.5 * inch, 1 * inch, 1 * inch, 1 * inch, 1 * inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgreen),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))

            self.story.append(table)

    def add_velocity_analysis(self, velocity_stats: Dict, velocity_chart_paths: List[str]):
        """FIXED: Enhanced velocity analysis section with proper error handling."""
        heading = Paragraph("Velocity & Acceleration Analysis", self.heading_style)
        self.story.append(heading)

        # Enhanced description
        description = """
        Velocity and acceleration analysis provides crucial insights into joint dynamics and movement efficiency.
        Research shows that knee angular velocities typically range from 9-14 rad/s during dynamic movements,
        while ankle velocities can reach up to 14.7 rad/s. These metrics are essential for:
        • Performance analysis and movement optimization
        • Injury prevention and rehabilitation monitoring  
        • Bilateral symmetry assessment
        • Movement efficiency evaluation
        """
        para = Paragraph(description, self.styles['Normal'])
        self.story.append(para)
        self.story.append(Spacer(1, 0.2 * inch))

        # Group keypoints by body region
        hip_keypoints = {k: v for k, v in velocity_stats.items() if 'hip' in k}
        wrist_keypoints = {k: v for k, v in velocity_stats.items() if 'wrist' in k}
        knee_keypoints = {k: v for k, v in velocity_stats.items() if 'knee' in k}
        ankle_keypoints = {k: v for k, v in velocity_stats.items() if 'ankle' in k}

        # Add charts grouped by body region
        for chart_path in velocity_chart_paths:
            if os.path.exists(chart_path):
                try:
                    img = Image(chart_path, width=6 * inch, height=4.5 * inch)
                    self.story.append(img)
                    self.story.append(Spacer(1, 0.2 * inch))
                except Exception as e:
                    print(f"Warning: Could not add velocity chart {chart_path}: {e}")

        # FIXED: Enhanced statistics tables with proper error handling
        if knee_keypoints or ankle_keypoints:
            knee_ankle_heading = Paragraph("Knee & Ankle Velocity Statistics", self.styles['Heading3'])
            self.story.append(knee_ankle_heading)

            # FIXED: Simplified table without problematic fields
            stats_data = [
                ['Joint', 'Side', 'Peak Vel (mm/s)', 'Mean Vel (mm/s)', 'Peak Acc (mm/s²)', 'Vel Std (mm/s)']
            ]

            # Add knee data with safe field access
            for keypoint_name, stats in knee_keypoints.items():
                side = 'Left' if 'left' in keypoint_name else 'Right'
                stats_data.append([
                    'Knee', side,
                    f"{stats.get('vel_max', 0):.1f}",
                    f"{stats.get('vel_mean', 0):.1f}",
                    f"{stats.get('acc_max', 0):.1f}",
                    f"{stats.get('vel_std', 0):.1f}"
                ])

            # Add ankle data with safe field access
            for keypoint_name, stats in ankle_keypoints.items():
                side = 'Left' if 'left' in keypoint_name else 'Right'
                stats_data.append([
                    'Ankle', side,
                    f"{stats.get('vel_max', 0):.1f}",
                    f"{stats.get('vel_mean', 0):.1f}",
                    f"{stats.get('acc_max', 0):.1f}",
                    f"{stats.get('vel_std', 0):.1f}"
                ])

            table = Table(stats_data, colWidths=[0.8 * inch, 0.8 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightsteelblue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                # Highlight knee rows
                ('BACKGROUND', (0, 1), (-1, 2), colors.lightcyan),
                # Highlight ankle rows
                ('BACKGROUND', (0, 3), (-1, 4), colors.lightyellow)
            ]))

            self.story.append(table)
            self.story.append(Spacer(1, 0.2 * inch))

            # Add clinical interpretation
            interpretation = """
            Clinical Interpretation:
            • Peak Velocity: Maximum instantaneous velocity during movement
            • Mean Velocity: Average velocity throughout the movement cycle
            • Velocity Std: Standard deviation indicates movement consistency
            • Bilateral Comparison: Significant differences between left/right may indicate asymmetries
            • Peak Velocities: Compare with normative data for performance assessment
            """

            interp_para = Paragraph(interpretation, self.styles['Normal'])
            self.story.append(interp_para)

        # Add hip and wrist data in separate sections if needed
        if hip_keypoints:
            self._add_hip_velocity_stats(hip_keypoints)

        if wrist_keypoints:
            self._add_wrist_velocity_stats(wrist_keypoints)

    def _add_hip_velocity_stats(self, hip_keypoints):
        """Add hip velocity statistics section."""
        if not hip_keypoints:
            return

        hip_heading = Paragraph("Hip Velocity Statistics", self.styles['Heading3'])
        self.story.append(hip_heading)

        stats_data = [['Side', 'Peak Vel (mm/s)', 'Mean Vel (mm/s)', 'Peak Acc (mm/s²)']]

        for keypoint_name, stats in hip_keypoints.items():
            side = 'Left' if 'left' in keypoint_name else 'Right'
            stats_data.append([
                side,
                f"{stats.get('vel_max', 0):.1f}",
                f"{stats.get('vel_mean', 0):.1f}",
                f"{stats.get('acc_max', 0):.1f}"
            ])

        table = Table(stats_data, colWidths=[1 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightcoral),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        self.story.append(table)
        self.story.append(Spacer(1, 0.2 * inch))

    def _add_wrist_velocity_stats(self, wrist_keypoints):
        """Add wrist velocity statistics section."""
        if not wrist_keypoints:
            return

        wrist_heading = Paragraph("Wrist Velocity Statistics", self.styles['Heading3'])
        self.story.append(wrist_heading)

        stats_data = [['Side', 'Peak Vel (mm/s)', 'Mean Vel (mm/s)', 'Peak Acc (mm/s²)']]

        for keypoint_name, stats in wrist_keypoints.items():
            side = 'Left' if 'left' in keypoint_name else 'Right'
            stats_data.append([
                side,
                f"{stats.get('vel_max', 0):.1f}",
                f"{stats.get('vel_mean', 0):.1f}",
                f"{stats.get('acc_max', 0):.1f}"
            ])

        table = Table(stats_data, colWidths=[1 * inch, 1.2 * inch, 1.2 * inch, 1.2 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightseagreen),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        self.story.append(table)
        self.story.append(Spacer(1, 0.2 * inch))

    def add_conclusions(self):
        """Add conclusions section."""
        heading = Paragraph("Analysis Conclusions", self.heading_style)
        self.story.append(heading)

        conclusions = """
        This biomechanical analysis provides comprehensive insights into human movement patterns
        captured through 3D motion tracking.<br/>
        The analysis includes:<br/>

        • Bilateral movement comparison for symmetry assessment<br/>
        • Joint angle calculations for mobility evaluation<br/>
        • Velocity and acceleration analysis for dynamic assessment<br/>
        • Statistical summaries for quantitative evaluation<br/><br/>

        The results can be used for:<br/>
        • Sports performance analysis<br/>
        • Rehabilitation monitoring<br/>
        • Biomechanical research<br/>
        • Movement pattern assessment<br/>
        """

        para = Paragraph(conclusions, self.styles['Normal'])
        self.story.append(para)

    def generate_report(self, data_stats: Dict, movement_stats: Dict = None,
                        joint_stats: Dict = None, chart_paths: List[str] = None,
                        joint_chart_path: str = None, velocity_stats: Dict = None,
                        velocity_chart_paths: List[str] = None, csv_file_path: str = ""):
        """Generate the complete report with velocity analysis."""
        # Add all existing sections
        self.add_title_page(csv_file_path)
        self.add_summary_section(data_stats)

        if movement_stats and chart_paths:
            self.add_movement_analysis(movement_stats, chart_paths)

        if joint_stats:
            self.story.append(PageBreak())
            self.add_joint_angle_analysis(joint_stats, joint_chart_path)

        # Add velocity analysis section
        if velocity_stats and velocity_chart_paths:
            self.story.append(PageBreak())
            self.add_velocity_analysis(velocity_stats, velocity_chart_paths)

        self.story.append(PageBreak())
        self.add_conclusions()

        # Build PDF
        self.doc.build(self.story)
        print(f"✓ Report generated: {self.output_path}")

        return self.output_path
